# Network Details
hiddenLayers: 2
hiddenLayerSizeFactor: 2
softMaxSensitivity: .25
softMaxOffset: -10
argMaxSampleSize: 4

# Training Details
maxStepsPerEpisode: 20
learningRate: 1.0e-5
entropyWeight: .1
discountFactor: .99

replayBufferSize: 100000
replayBatchSize: 1000


# Evaluation
#qualityMomentum: .99975
qualityMomentum: .99995