# Network Details
hiddenLayers: 2
hiddenLayerSizeFactor: 2

# Training Details
maxStepsPerEpisode: 20
learningRate: 1.0e-5
entropyWeight: .1
discountFactor: .99

replayBufferSize: 1000
replayBatchSize: 50


# Evaluation
#qualityMomentum: .999
qualityMomentum: .99995