# Network Details
hiddenLayers: 2
hiddenLayerSizeFactor: 2
softMaxSensitivity: .25
softMaxOffset: -10

# Training Details
maxStepsPerEpisode: 20
learningRate: 1.0e-5
entropyWeight: .1
discountFactor: .99

replayBufferSize: 1.0e+5
#replayBatchSize: 250
replayBatchSize: 5

argMaxSampleSize: 4
swapNetworkPeriod: 1.0e+3

# Evaluation
episodesPerTimeStep: 1.0e+6
qualityMomentum: .99995